"""
API Catalog Service — Centralized access to family API catalogs.

Loads type->namespace mappings from JSON catalog files (generated by Phase 0
bootstrap). Provides lookup methods for using directives, namespace validation,
and symbol validation.

HEAL-02: Replaces inline _load_catalog_directives() in semantic_microfixes.py
"""

import json
import logging
from pathlib import Path
from typing import Dict, List, Optional, Set

logger = logging.getLogger(__name__)


class APICatalogService:
    """Service for loading and querying API catalogs per product family."""

    def __init__(self, family: str, catalog_path: Optional[str] = None):
        """
        Initialize the catalog service for a given family.

        Args:
            family: Product family identifier (e.g., "zip")
            catalog_path: Explicit path to catalog JSON. If None, uses
                          config/families/{family}_api_catalog.json
        """
        self.family = family
        self._types: Dict[str, str] = {}          # type_name -> namespace
        self._namespaces: List[str] = []
        self._using_directives: Dict[str, str] = {}  # type_name -> using directive
        self._ambiguous_types: Dict[str, List[str]] = {}
        self._metadata: Dict = {}
        self._loaded = False

        if catalog_path:
            path = Path(catalog_path)
        else:
            path = Path(__file__).parent.parent.parent / "config" / "families" / f"{family}_api_catalog.json"

        if path.exists():
            self._load(path)
        else:
            logger.warning(f"No API catalog found for family '{family}' at {path}")

    def _load(self, path: Path) -> None:
        """Load catalog from JSON file."""
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
            self._metadata = data.get("_metadata", {})
            self._namespaces = data.get("namespaces", [])
            self._types = data.get("types", {})
            self._using_directives = data.get("using_directive_map", {})
            self._ambiguous_types = data.get("namespace_ambiguous_types", {})
            self._loaded = True
            logger.info(
                f"APICatalogService({self.family}): loaded {len(self._types)} types, "
                f"{len(self._namespaces)} namespaces from {path.name}"
            )
        except (json.JSONDecodeError, KeyError) as e:
            logger.error(f"Failed to load API catalog from {path}: {e}")

    @property
    def is_loaded(self) -> bool:
        return self._loaded

    def get_all_types(self) -> List[str]:
        """Return all type names in the catalog."""
        return list(self._types.keys())

    def get_all_namespaces(self) -> List[str]:
        """Return all namespaces in the catalog."""
        return list(self._namespaces)

    def get_namespace_for_type(self, type_name: str) -> Optional[str]:
        """Return the namespace for a given type, or None if not found."""
        return self._types.get(type_name)

    def get_using_directive(self, type_name: str) -> Optional[str]:
        """Return the using directive string for a type (e.g. 'using Aspose.Zip;')."""
        return self._using_directives.get(type_name)

    def get_using_directive_map(self) -> Dict[str, str]:
        """Return the full type->using_directive map (for bulk integration)."""
        return dict(self._using_directives)

    def get_namespace_map(self) -> Dict[str, str]:
        """Return the type->namespace mapping (without 'using' prefix/suffix)."""
        return dict(self._types)

    def validate_symbol(self, symbol: str) -> bool:
        """Check if a symbol (type name) exists in the catalog."""
        return symbol in self._types

    def is_ambiguous(self, type_name: str) -> bool:
        """Check if a type name exists in multiple namespaces."""
        return type_name in self._ambiguous_types

    def get_ambiguous_namespaces(self, type_name: str) -> List[str]:
        """Return all namespaces for an ambiguous type name."""
        return self._ambiguous_types.get(type_name, [])

    def validate_namespace(self, namespace: str) -> bool:
        """Check if a namespace is in the catalog's known namespaces."""
        return namespace in self._namespaces

    def get_namespace_set(self) -> Set[str]:
        """Return the set of all known namespaces (for whitelist integration)."""
        return set(self._namespaces)
